version: "3.9"
services:

  postgresqldb:
    container_name: postgresqldb
    image: postgres:15
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: delivery_service
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: pass
