version: "3.9"
services:
  app:
    container_name: delivery-service-api
    build: ./
    ports:
      - "9001:9001"
    depends_on:
      - postgresqldb
    networks:
      - postgres


  postgresqldb:
    container_name: postgresqldb
    image: postgres:15
    restart: always
    ports:
      - "7000:5432"
    environment:
      POSTGRES_DB: "delivery_service"
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "pass"

    networks:
      - postgres

  pgadmin:
    container_name: pgadmin_container
    image: dpage/pgadmin4:7.2
    environment:
      PGADMIN_DEFAULT_EMAIL: "vit.netrebin@gmail.com"
      PGADMIN_DEFAULT_PASSWORD: "pass"
      PGADMIN_CONFIG_SERVER_MODE: "False"
    ports:
      - "5050:80"
    restart: unless-stopped
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 1G
    networks:
      - postgres

networks:
  postgres:
    driver: bridge
