version: "3.9"
services:
  app:
    container_name: delivery-service-api
    build: ./
    ports:
      - "${APP_PORT}:8080"
    depends_on:
      - postgresqldb
    environment:
      APP_PORT: ${APP_PORT}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}



  postgresqldb:
    container_name: postgresqldb
    image: postgres:15
    restart: always
    ports:
      - "${POSTGRES_OUT_PORT}:5432"
    environment:
      POSTGRES_DB: "delivery_service"
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
