server:
  port: 9001
jwt:
  secret: 404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970
  lifetime: 86400000
  header: Authorization

spring:
  config:
    activate:
      on-profile: prod
  datasource:
    url: jdbc:postgresql://postgresqldb:5432/delivery_service
    username: postgres
    password: pass
    driver-class-name: org.postgresql.Driver
  jpa:
    open-in-view: false
    show-sql: true

  flyway:
    url: jdbc:postgresql://postgresqldb:5432/delivery_service
    user: postgres
    password: pass
    locations: classpath:migrations

url:
  schema: http
  host: localhost
  port: 9001