server:
  port: 8080
jwt:
  secret: 404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970
  lifetime: 86400000
  header: Authorization

spring:
  config:
    activate:
      on-profile: dev
  datasource:
    url: jdbc:postgresql://localhost:5432/delivery_service
    username: postgres
    password: pass
    driver-class-name: org.postgresql.Driver

  flyway:
    url: jdbc:postgresql://localhost:5432/delivery_service
    locations: classpath:migrations
    user: postgres
    password: pass

  jpa:
    open-in-view: false
    show-sql: true
url:
  schema: http
  host: localhost
  port: 8080